#NAME: Lauren Fromm
#EMAIL: laurenfromm@gmail.com
#ID: 404751250

default: lab1a.o
	gcc -g lab1a.o -o lab1a -Wall -Wextra

clean:
	rm -f lab1a *.o *.txt *.tar.gz

dist:
	tar -czvf lab1a-404751250.tar.gz README  Makefile lab1a.c
