#NAME: Lauren Fromm
#EMAIL: laurenfromm@gmail.com
#ID: 404751250

Default: lab3a

lab3a:
	gcc -Wall -Wextra -g lab3a.c -o lab3a

dist:
	tar -czvf lab3a-404751250.tar.gz lab3a.c Makefile README ext2_fs.h

clean:
	rm -f lab3a *.o *.txt *.tar.gz
